format = """
[ ](bg:#6A80EE)\
$os\
$username\
[](bg:#654FE8 fg:#6A80EE)\
$directory\
[](fg:#654FE8 bg:#6D32BC)\
$git_branch\
$git_status\
[](fg:#6D32BC bg:#7C1980)\
$cmake\
$dart\
$dotnet\
$elixir\
$golang\
$gradle\
$haskell\
$java\
$julia\
$lua\
$nim\
$nodejs\
$odin\
$python\
$rust\
$scala\
$swift\
$zig\
[](fg:#7C1980 bg:#5A1048)\
$time\
[ ](fg:#5A1048)\
"""

# add_newline = false

# You can also replace your username with a neat symbol like   or disable this
# and use the os module below
[username]
show_always = true
style_user = "bg:#6A80EE"
style_root = "bg:#6A80EE"
format = '[$user ]($style)'
disabled = false

# An alternative to the username module which displays a symbol that
# represents the current operating system
[os]
style = "bg:#6A80EE"
disabled = false # Disabled by default

[directory]
style = "bg:#654FE8"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[git_branch]
symbol = ""
style = "bg:#6D32BC"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#6D32BC"
format = '[$all_status$ahead_behind ]($style)'
disabled = true

[c]
symbol = " "
style = "bg:#7C1980"
format = '[ $symbol ($version) ]($style)'

[cmake]
symbol = "󰔶"
style = "bg:#7C1980"
format = '[ $symbol ($version) ]($style)'

[dart]
symbol = ""
style = "bg:#7C1980"
format = '[ $symbol ($version) ]($style)'

[dotnet]
symbol = ""
style = "bg:#7C1980"
format = '[ $symbol ($version) ]($style)'

[elixir]
symbol = " "
style = "bg:#7C1980"
format = '[ $symbol ($version) ]($style)'

[golang]
symbol = " "
style = "bg:#7C1980"
format = '[ $symbol ($version) ]($style)'

[gradle]
symbol = ""
style = "bg:#7C1980"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = ""
style = "bg:#7C1980"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = ""
style = "bg:#7C1980"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = ""
style = "bg:#7C1980"
format = '[ $symbol ($version) ]($style)'

# Very slow!
# [kotlin]
# symbol = " "
# style = "bg:#7C1980"
# format = '[ $symbol ($version) ]($style)'

[lua]
symbol = ""
style = "bg:#7C1980"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "bg:#7C1980"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = "󰆥"
style = "bg:#7C1980"
format = '[ $symbol ($version) ]($style)'

[odin]
style = "bg:#7C1980"
format = '[ $symbol ($version)]($style)'

[python]
symbol = ""
style = "bg:#7C1980"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ""
style = "bg:#7C1980"
format = '[ $symbol ($version) ]($style)'

[scala]
symbol = ""
style = "bg:#7C1980"
format = '[ $symbol ($version) ]($style)'

[swift]
symbol = ""
style = "bg:#7C1980"
format = '[ $symbol ($version) ]($style)'

[zig]
symbol = ""
style = "bg:#7C1980"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#5A1048"
format = '[ $time ]($style)'
